In [2]:
import numpy as np
import matplotlib.pyplot as plt
import numpy
import matplotlib
import pandas as pd
import scipy
from scipy.spatial import distance
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
from sklearn import datasets
from sklearn import linear_model
from sklearn import neighbors

%matplotlib inline

In [10]:
input_file = "data.csv"
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]
X_train = X[:-1]
X_test = [X[-1]]
y_train = y[:-1]
y_test = [y[-1]]
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[61. 48.]
 [62. 28.]
 [83. 84.]
 [68. 24.]
 [56. 39.]
 [32. 95.]
 [99. 14.]
 [87. 64.]
 [44. 35.]
 [70. 51.]]
[array([94., 37.])]
[1. 1. 0. 1. 1. 1. 1. 0. 0. 0.]
[0.0]


In [27]:
#Neighbors classifier
num_neighbors = 3
classifier = neighbors.KNeighborsClassifier(num_neighbors, weights='distance', p=1)

In [28]:
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3, p=1, weights='distance')

In [29]:
y_test_pred = classifier.predict(X_test)
print(y_test_pred)

[0.]


In [30]:
distances, indices = classifier.kneighbors(X_test,  n_neighbors=num_neighbors)
print(distances)
print(indices)

[[28. 34. 38.]]
[[6 7 9]]
